version: '3'
services:
  offboard_computer:
    build: 
      context: .
      dockerfile: components/computer.dockerfile
    command: roscore
    environment:
      - LAUNCH_PKG=test_pkg
      - LAUNCH_FILE=publisher.launch
    ports:
      - "11311:11311" # expose rosmaster to outside for convenience
  onboard_computer:
    build: 
      context: .
      dockerfile: components/computer.dockerfile
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
      - LAUNCH_PKG=test_pkg
      - LAUNCH_FILE=listener.launch
    command: rostopic list
    depends_on:
      - offboard_computer
  gzweb:
    build: 
      context: .
      dockerfile: components/gzweb.dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345 
    depends_on:
      - gzserver
  gzserver:
    build: 
      context: .
      dockerfile: components/gzserver.dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - WORLD_FILE=iris.world
  px4:
    build: 
      context: .
      dockerfile: components/px4.dockerfile
    tty: true
