version: '3'
services:
  offboard_computer:
    build: 
      context: .
      dockerfile: offboard_computer/Dockerfile
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - LAUNCH_PKG=test_pkg
      - LAUNCH_FILE=test.launch
    #gzweb:
    #gzbuild: 
    #gz  context: .
    #gz  dockerfile: gzweb/Dockerfile
    #gz  args: 
    #gz    - GZRESOURCES_DIR=./gzresources
    #gzports: 
    #gz  - "8080:8080"
    #gzenvironment:
    #gz  - GAZEBO_MASTER_URI=http://gzserver:11345
    #gz#logging:
    #gz#  driver: none
    #gz#gzserver:
    #gzbuild: 
    #gz  context: .
    #gz  dockerfile: gzserver/Dockerfile
    #gz  args: 
    #gz    - GZRESOURCES_DIR=./gzresources
    #gzvolumes:
    #gz  - /tmp/.X11-unix:/tmp/.X11-unix
    #gzports: 
    #gz  - "11345:11345"
    #gzenvironment:
    #gz  - WORLD_FILE=iris.world
  #px4:
  #  build: ./px4
