version: '3'
services:
  offboard_computer:
    build: 
      context: .
      dockerfile: components/computer.dockerfile
    container_name: offboard_computer
    #command: rostopic obstacle_publisher obtacle_publisher.launch
    command: roscore
    ports:
      - "11311:11311" # expose rosmaster to host-computer
    logging:
      driver: none
  onboard_computer_1:
    build: 
      context: .
      dockerfile: components/computer.dockerfile
    container_name: onboard_computer_1
    #command: echo \"node disabled from docker-compose.yml\"
    command: roslaunch --wait test_pkg takeoff.launch px4_addr:=px4_1 nodename:=pc1
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
    depends_on:
      - offboard_computer
        #onboard_computer_2:
        #  build: 
        #    context: .
        #    dockerfile: components/computer.dockerfile
        #  container_name: onboard_computer_2
        #  #command: echo \"node disabled from docker-compose.yml\"
        #  command: roslaunch --wait test_pkg takeoff.launch px4_addr:=px4_2 nodename:=pc2
        #  environment:
        #    - ROS_MASTER_URI=http://offboard_computer:11311
        #  depends_on:
        #    - offboard_computer
  gzweb:
    build: 
      context: .
      dockerfile: components/gzweb.dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    container_name: gzweb
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345 # has no effect
    depends_on:
      - gzserver
    logging:
      driver: none
  gzserver:
    build: 
      context: .
      dockerfile: components/gzserver.dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    container_name: gzserver
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
      - WORLD_FILE=iris_vs_static_obstacles.world
  px4_1:
    build: 
      context: .
      dockerfile: components/px4.dockerfile
    container_name: px4_1
    tty: true
    #px4_2:
    #  build: 
    #    context: .
    #    dockerfile: components/px4.dockerfile
    #  container_name: px4_2
    #  tty: true
