version: '3'
services:
  # ---------- ASCEND SYSTEMS ------------
  offboard_computer:
    image: ascendntnu/control_simulator_pc_node:latest
    container_name: offboard_computer
    command: roslaunch simulator_utils offboard.launch
  onboard_computer_1:
    image: ascendntnu/control_simulator_pc_node:latest
    container_name: onboard_computer_1
    command: roslaunch --wait simulator_utils jetson.launch px4_addr:=px4_1 namespace:=alpha
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
    depends_on:
      - offboard_computer
  px4_1:
    image: ascendntnu/px4:latest
    container_name: px4_1
    tty: true
    depends_on:
      - onboard_computer_1
    logging:
      driver: none

      # onboard_computer_2:
      #  image: ascendntnu/control_simulator_pc_node:latest
      #  container_name: onboard_computer_2
      #  command: roslaunch --wait simulator_utils jetson.launch px4_addr:=px4_2
      #  environment:
      #    - ROS_MASTER_URI=http://offboard_computer:11311
      #  depends_on:
      #    - offboard_computer
      # px4_2:
      #  image: ascendntnu/px4:latest
      #  container_name: px4_2
      #  tty: true
      #  depends_on:
      #    - onboard_computer_2
      #  logging:
      #    driver: none

      # onboard_computer_3:
      #  image: ascendntnu/control_simulator_pc_node:latest
      #  container_name: onboard_computer_3
      #  command: roslaunch --wait simulator_utils jetson.launch px4_addr:=px4_3
      #  environment:
      #    - ROS_MASTER_URI=http://offboard_computer:11311
      #  depends_on:
      #    - offboard_computer
      # px4_3:
      #  image: ascendntnu/px4:latest
      #  container_name: px4_3
      #  tty: true
      #  depends_on:
      #    - onboard_computer_3
      #  logging:
      #    driver: none

      # onboard_computer_4:
      #  image: ascendntnu/control_simulator_pc_node:latest
      #  container_name: onboard_computer_4
      #  command: roslaunch --wait simulator_utils jetson.launch px4_addr:=px4_4
      #  environment:
      #    - ROS_MASTER_URI=http://offboard_computer:11311
      #  depends_on:
      #    - offboard_computer
      # px4_4:
      #  image: ascendntnu/px4:latest
      #  container_name: px4_4
      #  tty: true
      #  depends_on:
      #    - onboard_computer_4
      #  logging:
      #    driver: none

  # ---------- SIMULATOR BACKEND ------------
  gzweb:
    image: ascendntnu/gzweb:latest
    container_name: gzweb
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345 # has no effect
    depends_on:
      - gzserver
    logging:
      driver: none
  gzserver:
    image: ascendntnu/gzserver:latest
    container_name: gzserver
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
      - WORLD_FILE=single_world.world
    logging:
      driver: none
      #  mocap_node:
      #image: ascendntnu/control_simulator_pc_node:latest
      #container_name: mocap_node
      #command: rosrun simulator_utils mocap_publisher_node
      #environment:
      #  - ROS_MASTER_URI=http://offboard_computer:11311

