version: '3'
services:
  gzweb:
    build: 
      context: .
      dockerfile: gzweb/Dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    ports: 
      - "8080:8080"
  gzserver:
    build: 
      context: .
      dockerfile: gzserver/Dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    ports: 
      - "11345:11345"
