version: '3'
services:
  gzweb:
    build: 
      context: .
      dockerfile: gzweb/Dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345
    #logging:
    #  driver: none
  gzserver:
    build: 
      context: .
      dockerfile: gzserver/Dockerfile
      args: 
        - GZRESOURCES_DIR=./gzresources
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports: 
      - "11345:11345"
    environment:
      - WORLD_FILE=iris.world
  #px4:
  #  build: ./px4
