version: '3'
services:
  offboard_computer:
    image: ascendntnu/control_simulator_pc_node
    container_name: offboard_computer
    #command: roslaunch obstacle_publisher obtacle_publisher.launch
    command: roscore
    ports:
      - "11311:11311" # expose rosmaster to host-computer
    logging:
      driver: none
  onboard_computer_1:
    image: ascendntnu/control_simulator_pc_node
    container_name: onboard_computer_1
    #command: echo ""
    command: roslaunch --wait test_pkg takeoff.launch px4_addr:=px4_1 nodename:=pc1
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
    depends_on:
      - offboard_computer
  onboard_computer_2:
    image: ascendntnu/control_simulator_pc_node
    container_name: onboard_computer_2
    #command: echo ""
    command: roslaunch --wait test_pkg takeoff.launch px4_addr:=px4_2 nodename:=pc2
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
    depends_on:
      - offboard_computer
  gzweb:
    image: ascendntnu/gzweb
    container_name: gzweb
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345 # has no effect
    depends_on:
      - gzserver
    logging:
      driver: none
  gzserver:
    image: ascendntnu/gzserver
    container_name: gzserver
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
      - WORLD_FILE=iris_vs_static_obstacles.world
  px4_1:
    image: ascendntnu/px4
    container_name: px4_1
    tty: true
