version: '3'
services:
  offboard_computer:
    image: ascendntnu/control_simulator_pc_node:edge
    container_name: offboard_computer
    command: roslaunch obstacle_publisher obstacle_publisher.launch
    ports:
      - "11311:11311" # expose rosmaster to host-computer
  onboard_computer_1:
    image: ascendntnu/control_simulator_pc_node:edge
    container_name: onboard_computer_1
    command: roslaunch --wait simulator_utils jetson.launch px4_addr:=px4_1
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
    depends_on:
      - offboard_computer
  px4_1:
    image: ascendntnu/px4:edge
    container_name: px4_1
    tty: true
    depends_on:
      - onboard_computer_1

  # ---------- SIMULATOR BACKEND ------------
  gzweb:
    image: ascendntnu/gzweb:edge
    container_name: gzweb
    ports: 
      - "8080:8080"
    environment:
      - GAZEBO_MASTER_URI=http://gzserver:11345 # has no effect
    depends_on:
      - gzserver
    logging:
      driver: none
  gzserver:
    image: ascendntnu/gzserver:edge
    container_name: gzserver
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_MASTER_URI=http://offboard_computer:11311
      - WORLD_FILE=single_world.world
        #  mocap_node:
        #    image: ascendntnu/control_simulator_pc_node:edge
        #    container_name: mocap_node
        #    command: roslaunch --wait mocap_node mocap_node.launch 
        #    environment:
        #      - ROS_MASTER_URI=http://offboard_computer:11311
        #
