FROM px4io/px4-dev-nuttx
MAINTAINER "rendellc@ascendntnu.no"

# get px4, TODO: use ascends private px4 instead
ENV PX4_DIR /home/user/Firmware
RUN git clone https://github.com/PX4/Firmware.git $PX4_DIR

# compile
WORKDIR $PX4_DIR
RUN git checkout v1.8.1 \
  && /bin/bash -c "DONT_RUN=1 make posix_sitl_default" 

CMD ["./Tools/sitl_run.sh", \
  "ROMFS/px4_common/init.d/10016_3dr_iris", \
  "ROMFS/px4_common/init.d", \
  "none", \
  "gazebo", \
  "iris", \
  ".", \
  "./build/posix_sitl_default"]
