#!/bin/bash

GZRESOURCE_DIR="$(dirname $(pwd))"

echo "GZRESOURCE_DIR: $GZRESOURCE_DIR"
echo "FILES: "
ls

GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$GZRESOURCE_DIR/plugins
GAZEBO_MODEL_PATH=${GAZEBO_PLUGIN_PATH}:$GZRESOURCE_DIR/models

